### PR TITLE
Add OpenAPI spec + Redocusaurus + Search facet tutorial

### PR DESCRIPTION
**Pull request by venashial**
The OpenAPI spec is almost even with the [GitHub wiki](https://github.com/modrinth/labrinth/wiki/API-Documentation). Tags have not been added to the OpenAPI spec. The spec follows v2 changes.

Deploy: 
- API: https://docs-git-openapi-venashial.vercel.app/api/
- Search facet tutorial: https://docs-git-openapi-venashial.vercel.app/docs/tutorials/search-facets/

image

image

### CODE REVIEW

**Comment by ImpossibleReality** [comment]
I feel like the redoc kinda looks ugly when used together with the docusaurus theme. It might be better to manually write the api docs, and use openapi for making modrinth libraries. I don't think it'll be too much of a hassle, since we won't release new API versions very quickly, and there will be lots of time to document changes. Plus we're going to have to document migration steps manually anyways.

**Comment by wafflecoffee** [comment]
@ImpossibleReality I wholeheartedly disagree.

Usability and ease of use is much more important than looks. Themes can change, and the theme should not be a barrier to entry in terms of getting this done. Having the OpenAPI spec is much easier and more accessible for both us to edit and for others (human and non-human alike) to read. I agree that a better look is certainly possible, but it most certainly should not be a reason to prevent us from doing an OpenAPI spec.
Manually writing docs for something like this would be **far** more of a hassle than tweaking the yml file every so often. Migration steps are manual for a reason: they are meant to specifically be read by a human to change things from one version to another, as, as far as I know, there is no machine-readable way to do that. OpenAPI is a thing for a reason, after all.

**Comment by ImpossibleReality** [comment]
> Having the OpenAPI spec is much easier and more accessible for both us to edit and for others (human and non-human alike) to read.

Manually written docs are **much** easier to read and understand, especially if they are well written, but I do see your point of it being a hassle to edit. If you look at many large services (like discord and stripe), they manually write out API Docs, but still use OpenAPI internally to make libraries (at least in the case of stripe). Plus, Modrinth has a relatively small API. Again, we aren't going to be doing major updates on APIs quickly, so it may be better to manually write them, even if it may be more annoying.

**Comment by Redblueflame** [comment]
I'm currently taking a look, mainly removing the doc about search, as I did make another one, that is written differently, and more as a tutorial on how it should all work
Other than that, I may end up making it as the API Spec page on the topbar.

**Comment by Redblueflame** [comment]
I had to merge it manually, so your contribution did not go through.
Do you mind? If your answer is yes, I may try to merge it and forcepush it

**Comment by venashial** [comment]
I don't really mind, no

**Pull request closed without merging**
