### PR TITLE
Improve Docs

### PR DESCRIPTION
**Pull request by ImpossibleReality**
TODO:
- [x] Fix Homepage
- [x] Better Getting Started Page
- [ ] Better way of representing HTTP Requests
- [ ] Standards for the API docs

### CODE REVIEW

**Comment by Redblueflame** [comment]
Looks like the SVGs for the main page aren't included in the commit

**Comment by ImpossibleReality** [comment]
oops lol forgot to `git add` them XD

**Comment by Redblueflame** [comment]
One last thing, the fact that you did move the getting started document broke links in the navigation bar.
You may need to change the link

**Comment by ImpossibleReality** [comment]
Navigation bar seems to work, could you please elaborate?

**Comment by Redblueflame** [comment]
I was wrong, the issue is in the footer, where there's still the `/docs/intro` page

**Review by Redblueflame — APPROVED** [review]
Looks good in its current state.
Do not hesitate to contact me if you have any question

**Comment by Geometrically** [comment]
Superseded by #9

**Pull request closed without merging**
