### PR TITLE
Add xmcl back

### PR DESCRIPTION
**Pull request by ci010**
XMCL removed the Offline login for the regions with DMCA protection. Therefore, we can add this back to the docs.

Currently, the XMCL use a [deny list](https://github.com/Voxelum/x-minecraft-launcher/blob/master/xmcl-runtime/lib/util/offlineModeDenylist.ts) to control this feature.

(Removed since f6a37ea39b1900edaa834479b66a99c3cf50ff9e)

### CODE REVIEW

**Comment by Patbox** [comment]
It's still piracy launcher, even if region specific

**Comment by ci010** [comment]
> It's still piracy launcher, even if region specific

The bakaxl launcher is the same situation. I wonder what follow up action XMCL could make to make it suitable?

**Comment by killpowa** [comment]
Well, it should probably remove offline login altogether as only making it region specific does not make it legit and it still violates Mojang's ToS

**Comment by Brawaru** [comment]
Or do it like Prism Launcher: only allow to add offline accounts when at least one Microsoft account is added. Offline accounts are useful for mod and server plugin developers, but they should not be used for piracy.

**Comment by SylvKT** [comment]
## "rare" occasions where offline mode is useful
* mod development (wow who does that lol imagine making mods)
* bad internet / the ISP is offline again / when you turn on the microwave and you have bad internet and you don't care about playing multiplayer
* debugging
* testing

**Comment by Patbox** [comment]
> ## "rare" occasions where offline mode is useful
> * mod development (wow who does that lol imagine making mods)
> * bad internet / the ISP is offline again / when you turn on the microwave and you have bad internet and you don't care about playing multiplayer
> * debugging
> * testing
> 
> Not only can it be used for piracy, but it can be handy in many other situations!

* Launcher still should require at least one account with the game.
* You need internet to download the game in the first place, so requiring to be online at least at initial instalation should be required
* Same as first one
* Same as first one

**Comment by triphora** [comment]
Let's not turn this into a debate about whether offline mode is good or bad.

For this to get merged, XMCL has to have it so that it's not possible for anyone to launch the game (not including demo mode) without first having connected a Microsoft account with Minecraft purchased.

Capiche?

**Comment by triphora** [comment]
Since that does not seem to have been done in the months that this PR has been open, closing.

**Pull request closed without merging**
