### PR TITLE
Update to Docusaurus v3

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title.

I think we can update the documentation with the release candidate (no futur breaking changes normally).

https://github.com/facebook/docusaurus/discussions/9429
https://twitter.com/sebastienlorber/status/1715309311767831033

### CODE REVIEW

**Comment by triphora** [comment]
image
Seem to be getting this error when navigating to the API spec.

**Comment by Mysterious-Dev** [comment]
Yeah, I think it is necessary to wait for a redocusaurus patch or suggest one (I'll take a look).

**Comment by Mysterious-Dev** [comment]
@triphora I updated the dependencies and it works now.

**Review by triphora — APPROVED** [review]
Great, thanks! It seems there is still a weird warning in the console when starting the dev server, but this is irrelevant.

**Pull request merged**
